site_name: Kavish Gour - Notes

nav:
    - Home: index.md
    - Bash Alias: bash_alias.md
    - Golang: golang.md
    - Grep : grep.md
    - Sed: sed.md
    - Vim: vim.md
    - Xargs: xargs.md
theme: readthedocs
