site_name: Kavish Gour - Notes

nav:
    - Home: index.md
    - Bash Alias: bash_alias.md
    - Golang: golang.md
    - Grep : grep.md
    - Sed: sed.md
    - Vim: vim.md
    - Xargs: xargs.md
    - Regex for Burp: regexburp.md
    - Testing for Password Reset Functionalities: test_for_passwd_reset.md
    - SQLi: sqli.md
    - NahamSec Recon Session 1 Notes: nahamsec/recon_session_1.md
    - NahamSec Recon Session 2 Notes: nahamsec/recon_session_2.md
    - BugBountyNotes Mentoring Session: bugbountynotes/firstlivementoring.md
    - BugBountyNotes FastFoodHacking Session 1: bugbountynotes/fastfoodhackingsession1.md
    - BugBountyNotes Challenge Session 1: bugbountynotes/challengesession1.md
    - BugBountyNotes Filter Bypass Session: bugbountynotes/filterbypass.md
    - Tomnomnom Q&A Session: tomnomnom/session1.md
    - Stok IDOR Session:  idor.md
    - Tomnomnom Vim Tutorial: vim_tutorial.md
theme: readthedocs
